---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: discourse

  labels:
    type: discourse-all

spec:
  persistentVolumeReclaimPolicy: Retain

  hostPath:
    type: DirectoryOrCreate
    path: /mnt/discourse

  accessModes:
  - ReadWriteMany

  capacity:
    storage: 10Gi
---

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  namespace: discourse
  name: discourse

spec:
  storageClassName: ""

  accessModes:
  - ReadWriteMany

  resources:
    requests:
      storage: 10Gi

  selector:
    matchLabels:
      type: discourse-all
---
