---
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  namespace: discourse
  name: pgsql

data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
---


---
apiVersion: v1
kind: Secret
type: Opaque

metadata:
  namespace: discourse
  name: discourse

data:
  DISCOURSE_USERNAME: dXNlcg==
  DISCOURSE_PASSWORD: Yml0bmFtaTEyMw==
  DISCOURSE_POSTGRESQL_USERNAME: cG9zdGdyZXM=
  DISCOURSE_POSTGRESQL_PASSWORD: cG9zdGdyZXM=
  POSTGRESQL_ROOT_USER: cG9zdGdyZXM=
  POSTGRESQL_ROOT_PASSWORD: cG9zdGdyZXM=
---
