---
apiVersion: v1
kind: Service

metadata:
  namespace: discourse
  name: redis

spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None

  ports:

  - name: redis
    port: 6379
    targetPort: redis

  selector:
    app: redis
    cat: cache
---


---
apiVersion: v1
kind: Service

metadata:
  namespace: discourse
  name: pgsql

spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None

  ports:

  - name: pgsql
    port: 5432
    targetPort: pgsql

  selector:
    app: pgsql
    cat: db
---


---
apiVersion: v1
kind: Service

metadata:
  namespace: discourse
  name: discourse

spec:
  type: ClusterIP
  #clusterIP: None
  #sessionAffinity: None

  ports:

  - name: http-discourse
    port: 3000
    targetPort: http-discourse

  selector:
    app: discourse
    cat: web
---
