---
apiVersion: apps/v1beta1
kind: Deployment

metadata:
  namespace: discourse
  name: pgsql

spec:
  replicas: 1
  minReadySeconds: 15

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: pgsql
      cat: db

  template:

    metadata:
      labels:
        app: pgsql
        cat: db

    spec:
      terminationGracePeriodSeconds: 5

      volumes:

      - name: discourse-pv
        persistentVolumeClaim:
          claimName: discourse

      containers:

      - name: pgsql
        #image: postgres:alpine
        image: postgres:9.6-alpine
        imagePullPolicy: IfNotPresent

        resources:
          requests:
            cpu: 200m
            memory: 256Mi

        envFrom:

        - configMapRef:
            name: pgsql

        - secretRef:
            name: pgsql
        
        volumeMounts:

        - name: discourse-pv
          subPath: pgsql
          mountPath: /var/lib/postgresql/data

        ports:

        - name: pgsql
          containerPort: 5432
          protocol: TCP

        readinessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 20
          periodSeconds: 15
          tcpSocket:
            port: pgsql

        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 1
          failureThreshold: 3
          periodSeconds: 50
          tcpSocket:
            port: pgsql
---
