---
apiVersion: apps/v1beta1
kind: Deployment

metadata:
  namespace: discourse
  name: discourse

spec:
  replicas: 1
  minReadySeconds: 15

  strategy:
    type: RollingUpdate
    #rollingUpdate:
    #  maxSurge:
    #  maxUnavailable:

  selector:
    matchLabels:
      app: discourse
      cat: web

  template:

    metadata:
      labels:
        app: discourse
        cat: web

    spec:
      terminationGracePeriodSeconds: 15

      volumes:

      - name: discourse-pv
        persistentVolumeClaim:
          claimName: discourse

      containers:

      # main
      - name: discourse
        image: bitnami/discourse:latest
        imagePullPolicy: IfNotPresent

        resources:

          requests:
            cpu: 500m
            memory: 1Gi

          limits:
            cpu: 1
            memory: 2Gi

        envFrom:

        - configMapRef:
            name: discourse

        - secretRef:
            name: discourse

        volumeMounts:

        - name: discourse-pv
          subPath: app
          mountPath: /bitnami

        ports:

        - name: http-discourse
          containerPort: 3000
          protocol: TCP

        readinessProbe:
          initialDelaySeconds: 600
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 20
          periodSeconds: 15
          tcpSocket:
            port: http-discourse

        livenessProbe:
          initialDelaySeconds: 600
          timeoutSeconds: 1
          failureThreshold: 3
          periodSeconds: 50
          tcpSocket:
            port: http-discourse

      # sidecar
      - name: sidekiq
        image: bitnami/discourse
        imagePullPolicy: IfNotPresent

        args:
        - nami
        - start
        - --foreground
        - discourse-sidekiq

        resources:

          requests:
            cpu: 100m
            memory: 100Mi

          limits:
            cpu: 100m
            memory: 100Mi

        envFrom:

        - configMapRef:
            name: discourse

        - secretRef:
            name: discourse

        volumeMounts:

        - name: discourse-pv
          subPath: sidekiq
          mountPath: /bitnami
---
